Library Management Service initial implementation
OpenCodeFoundation/eSchool pull request #427
Opened 2021-06-08 16:35 UTC by sohan093007

2021-06-08 16:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenCodeFoundation/eSchool?pullRequest=427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenCodeFoundation/eSchool?pullRequest=427) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenCodeFoundation/eSchool?pullRequest=427) it.</sub>

2021-06-08 16:52 UTC, sohan093007 reviewed
Library Management Service initial implementation

2021-06-11 17:04 UTC, NitaiBanik commented on src/Services/LibraryManagement/LibraryManagement.API/Startup.cs
> +                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "LibraryManagement.API v1"));
Can you please fix the indentation here?

2021-06-11 17:04 UTC, NitaiBanik commented on src/Services/LibraryManagement/LibraryManagement.API/Controllers/HelloWorldController.cs
> +        {
please return `ActionResult<string>` instaed of `static string`

2021-06-12 05:33 UTC, sohan093007 reviewed
Made some changes according to Nitai's Comment.

2021-06-12 16:20 UTC, sohan093007 reviewed
LibraryMangment after indentation

2021-06-12 16:21 UTC, sohan093007 reviewed
LibraryMangment after indentation

2021-07-03 13:37 UTC, ratanparai requested changes

2021-07-03 13:37 UTC, ratanparai commented on src/Services/LibraryManagement/LibraryManagement.API/Startup.cs
> +            app.UseHttpsRedirection();
remove https redirection.

2021-07-03 14:30 UTC, sohan093007 reviewed
After removing HTTPS redirection

2021-07-03 14:31 UTC, sohan093007 reviewed
After removing https redirection

2021-07-24 12:37 UTC, ratanparai approved these changes

2021-07-24 12:38 UTC, merged